'use strict';
const $=s=>document.querySelector(s);let csrf='',articles=[],uploading=false,pollTimer;
const labels={published:'Yayında',draft:'Taslak',archived:'Arşiv'};
function status(message,error=false,target='#status'){$(target).textContent=message;$(target).classList.toggle('error',error);}
async function api(path,options={}){const headers={...options.headers};if(options.method&&options.method!=='GET')headers['X-CSRF-Token']=csrf;const r=await fetch('/api/admin/'+path,{...options,headers,credentials:'same-origin',cache:'no-store'});const data=await r.json();if(!r.ok){if(r.status===401&&path!=='login')showLogin();throw Error(data.error||'İşlem tamamlanamadı.');}return data;}
function post(path,data){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});}
function showLogin(){$('#workspace').hidden=true;$('#login-panel').hidden=false;$('#logout').hidden=true;csrf='';clearTimeout(pollTimer);}
async function showWorkspace(){$('#workspace').hidden=false;$('#login-panel').hidden=true;$('#logout').hidden=false;await refresh();}
function text(tag,value,cls){const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;}
function render(){const list=$('#article-list');list.replaceChildren();const query=$('#search').value.toLocaleLowerCase('tr');const filter=$('#filter').value;const matches=articles.filter(a=>(filter==='all'||a.status===filter)&&(a.title+' '+a.source_name).toLocaleLowerCase('tr').includes(query));if(!matches.length){list.append(text('p','Bu görünümde haber yok.'));return;}matches.forEach(a=>{const row=text('article','','article-row');const image=document.createElement('img');image.src=a.image||'/logo.jpeg';image.alt='';image.loading='lazy';const copy=document.createElement('div');copy.append(text('span',labels[a.status],'badge'),text('h3',a.title),text('p',a.published+' · '+(a.source_name||'Ilgın İnsanı')));const edit=text('button','Düzenle');edit.addEventListener('click',()=>openEditor(a));row.append(image,copy,edit);list.append(row);});}
async function refresh(){const d=await api('news');articles=d.articles;$('#auto-publish').checked=d.auto_publish;const sync=d.last_sync;$('#sync-status').textContent=d.syncing?'Kaynak kontrol ediliyor…':sync.at?('Son kontrol: '+new Date(sync.at).toLocaleString('tr-TR')+' · '+(sync.ok?'Tamamlandı':sync.message)+(sync.errors?' · '+sync.errors+' içerik/görsel alınamadı.':'')):'İlk kaynak kontrolü bekleniyor.';render();if(d.syncing){clearTimeout(pollTimer);pollTimer=setTimeout(()=>refresh().catch(e=>status(e.message,true)),3000);}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const d=await post('login',{password:$('#password').value});$('#password').value='';csrf=d.csrf;status('');await showWorkspace();}catch(err){status(err.message,true);}finally{button.disabled=false;}});
$('#logout').addEventListener('click',async()=>{try{await post('logout',{});showLogin();status('Çıkış yapıldı.');}catch(e){status(e.message,true);}});
$('#search').addEventListener('input',render);$('#filter').addEventListener('change',render);
$('#auto-publish').addEventListener('change',async()=>{try{await post('settings',{auto_publish:$('#auto-publish').checked});status('Yayın tercihi kaydedildi.');}catch(e){$('#auto-publish').checked=!$('#auto-publish').checked;status(e.message,true);}});
$('#sync-now').addEventListener('click',async()=>{const b=$('#sync-now');b.disabled=true;try{await post('sync',{});status('Haber kaynağı kontrol ediliyor.');await refresh();}catch(e){status(e.message,true);}finally{b.disabled=false;}});
const fields={id:'article-id',title:'title',summary:'summary',body:'body',published:'published',category:'category',status:'article-status',image:'image-path',source_name:'source-name',source_url:'source-url'};
function openEditor(a={}){for(const [key,id] of Object.entries(fields))$('#'+id).value=a[key]||({published:new Date().toLocaleDateString('en-CA'),category:'Ilgın',status:'draft'}[key]||'');$('#editor-heading').textContent=a.id?'Haberi düzenle':'Yeni haber yaz';$('#image-preview').hidden=!a.image;$('#image-preview').src=a.image||'';$('#image-upload').value='';$('#source-name').readOnly=!!a.id&&a.source_name==='Ilgın Kaymakamlığı';$('#source-url').readOnly=$('#source-name').readOnly;$('#archive').hidden=!a.id;status('',false,'#editor-status');$('#editor').showModal();}
$('#new-article').addEventListener('click',()=>openEditor());$('#close-editor').addEventListener('click',()=>$('#editor').close());
$('#image-upload').addEventListener('change',async()=>{const file=$('#image-upload').files[0];if(!file)return;uploading=true;status('Fotoğraf yükleniyor…',false,'#editor-status');try{const data=new FormData();data.append('image',file);const result=await api('image',{method:'POST',body:data});$('#image-path').value=result.image;$('#image-preview').src=result.image;$('#image-preview').hidden=false;status('Fotoğraf hazır.',false,'#editor-status');}catch(e){status(e.message,true,'#editor-status');}finally{uploading=false;}});
async function save(){if(uploading){status('Fotoğrafın yüklenmesini bekle.',true,'#editor-status');return;}const d={};for(const [key,id] of Object.entries(fields))d[key]=$('#'+id).value;await post('news',d);$('#editor').close();await refresh();status('Haber kaydedildi.');}
$('#edit-form').addEventListener('submit',async e=>{e.preventDefault();e.submitter.disabled=true;try{await save();}catch(err){status(err.message,true,'#editor-status');}finally{e.submitter.disabled=false;}});
$('#archive').addEventListener('click',async()=>{if(!$('#edit-form').reportValidity())return;$('#article-status').value='archived';try{await save();}catch(e){status(e.message,true,'#editor-status');}});
api('session').then(d=>{csrf=d.csrf;return showWorkspace();}).catch(()=>showLogin());
